
class apache::default {
  $apache_ensure                      = 'present'
  $use_dev                            = false
  $apache_dev_ensure                  = 'present'
  $user                               = 'www-data'
  $group                              = 'www-data'
  $locale                             = ''
  $web_home                           = '/var/www'
  $access_file                        = '.htaccess'
  $timeout                            = 300
  $keepalive                          = true
  $max_keepalive_requests             = 100
  $keepalive_timeout                  = 5
  $mpm_prefork_start_servers          = 5
  $mpm_prefork_min_spare_servers      = 5
  $mpm_prefork_max_spare_servers      = 10
  $mpm_prefork_max_clients            = 150
  $mpm_prefork_max_requests_per_child = 0
  $mpm_worker_start_servers           = 2
  $mpm_worker_min_spare_threads       = 25
  $mpm_worker_max_spare_threads       = 75
  $mpm_worker_thread_limit            = 64
  $mpm_worker_threads_per_child       = 25
  $mpm_worker_max_clients             = 150
  $mpm_worker_max_requests_per_child  = 0
  $mpm_event_start_servers            = 2
  $mpm_event_min_spare_threads        = 25
  $mpm_event_max_spare_threads        = 75
  $mpm_event_thread_limit             = 64
  $mpm_event_threads_per_child        = 25
  $mpm_event_max_clients              = 150
  $mpm_event_max_requests_per_child   = 0
  $ulimit_max_files                   = 8192
  $restricted_files                   = [ '^\.ht' ]
  $default_type                       = 'None'
  $hostname_lookups                   = false
  $log_level                          = 'warn'
  $log_formats                        = {
    "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" => 'vhost_combined',
    "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\""       => 'combined',
    "%h %l %u %t \"%r\" %>s %O"                                          => 'common',
    "%{Referer}i -> %U"                                                  => 'referer',
    "%{User-agent}i"                                                     => 'agent',
  }
  $config_template                    = 'apache/apache2.conf.erb'
  $vars_template                      = 'apache/envvars.erb'
  $vhost_ip                           = '*'
  $default_port                       = 80
  $http_port                          = 80
  $use_ssl                            = ''
  $https_port                         = 443
  $priority                           = 25
  $options                            = 'Indexes FollowSymLinks MultiViews'
  $port_template                      = 'apache/ports.conf.erb'
  $vhost_template                     = 'apache/vhost.conf.erb'
  $vhost_proxy_template               = 'apache/vhost-proxy.conf.erb'
  $vhost_redirect_template            = 'apache/vhost-redirect.conf.erb'
}
